# Generated by Django 4.1.7 on 2023-03-12 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plataforma.uttils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_paciente', models.CharField(max_length=50, verbose_name='Nome de Paciente')),
                ('telefone', models.CharField(max_length=19)),
                ('cpf', models.CharField(max_length=14, validators=[plataforma.uttils.validate_cpf], verbose_name='CPF')),
                ('data_de_nacimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1)),
                ('data', models.DateField(verbose_name='Data de início do tratamento')),
                ('hma', models.TextField()),
                ('queixa_principal', models.TextField()),
                ('objetivo', models.TextField()),
                ('fisio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome_do_paciente'],
            },
        ),
        migrations.CreateModel(
            name='EscalaDeEva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor da EVA')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.paciente')),
            ],
            options={
                'verbose_name_plural': 'Escalas de EVA',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DadosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pa', models.CharField(max_length=7)),
                ('bpm', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.paciente')),
            ],
        ),
    ]
