# Generated by Django 4.0.5 on 2022-07-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospaciente',
            old_name='bpm_maxima',
            new_name='bpm',
        ),
        migrations.RenameField(
            model_name='dadospaciente',
            old_name='bpm_minima',
            new_name='pa',
        ),
        migrations.RemoveField(
            model_name='dadospaciente',
            name='pa_maxima',
        ),
        migrations.RemoveField(
            model_name='dadospaciente',
            name='pa_minima',
        ),
    ]
